In [ ]:
#pip install ISLP

In [1]:
print('fit a model with', 10, 'variables')

fit a model with 10 variables


In [2]:
print?

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

In [3]:
3+5

8

In [4]:
x = [1,2,3]
y = [3,4,5]
x+y

[1, 2, 3, 3, 4, 5]

In [5]:
#numpy - numerical Python
import numpy as np
x = np.array([[1,2],[3,0]])
y = np.array([[10,20],[30,0]])
x+y

array([[11, 22],
       [33,  0]])

In [6]:
print(x.ndim)
print(x.dtype)
print(x.shape)

2
int64
(2, 2)


In [7]:
x+y.sum()

array([[61, 62],
       [63, 60]])

In [8]:
arr = np.array([[10,20,30],[40,50,60]])
arr_reshape = arr.reshape(-1)
arr[0,0] = 100
print(arr)

[[100  20  30]
 [ 40  50  60]]


In [9]:
tuple_y = (1,2,3)
y(0) = 6

SyntaxError: cannot assign to function call here. Maybe you meant '==' instead of '='? (972436293.py, line 2)

In [10]:
#normal distribution
#loc = mean
#scale = standard deviation
random_arr = np.random.normal(size = (5,2),loc = 100, scale = 5)
random_arr

array([[101.72145192, 108.48805302],
       [ 98.40736153,  89.99260151],
       [101.85983882,  98.47875984],
       [100.2354696 ,  97.85016511],
       [104.04154815, 103.25361157]])

In [11]:
x = np.random.normal(size =50)
print(x)
y = x + np.random.normal(loc =50, scale =1, size =50)
np. corrcoef (x, y)
#corrcoeff is between variables x and y altogether. not the individual values

[-1.23517542 -0.33759305  2.16955202 -0.96277728  1.12075948  0.5700948
 -0.89710697 -0.33562002  1.16651049  0.93475145 -1.29274898 -1.98367397
 -1.88770669  1.1221045   1.00055059 -0.14455477  0.40709027  1.37159305
 -1.1533957  -2.39229615  0.53804326  0.00434496  1.06530089 -0.26709269
  0.45368694 -1.42106642 -1.22077427 -0.45972719  2.18638077  1.08845836
  1.46585778  0.87644057  0.46351662  0.52244508  0.96728108 -1.16537022
 -0.16038979  0.27110044  0.63924783 -1.05418498 -1.8163963   0.97868802
 -0.30437078  1.15263389 -0.42357348  0.45746762 -0.81879805 -1.63878112
  0.6915635  -0.65149488]


array([[1.        , 0.72713361],
       [0.72713361, 1.        ]])

In [12]:
#default_rng accepts some arbitrary integer which would give same set of random numbers every time the code is run
rand_arr_same_each_run = np.random.default_rng(42).normal(size = 20)
print(rand_arr_same_each_run)

[ 0.30471708 -1.03998411  0.7504512   0.94056472 -1.95103519 -1.30217951
  0.1278404  -0.31624259 -0.01680116 -0.85304393  0.87939797  0.77779194
  0.0660307   1.12724121  0.46750934 -0.85929246  0.36875078 -0.9588826
  0.8784503  -0.04992591]


In [16]:
random_num_generator = np.random.default_rng(42)
#standard_normal = mean 0, standard deviation 1
arr_50 = random_num_generator.standard_normal(size=20)
print(arr_50)

[ 0.30471708 -1.03998411  0.7504512   0.94056472 -1.95103519 -1.30217951
  0.1278404  -0.31624259 -0.01680116 -0.85304393  0.87939797  0.77779194
  0.0660307   1.12724121  0.46750934 -0.85929246  0.36875078 -0.9588826
  0.8784503  -0.04992591]


In [15]:
arr_50.mean(), arr_50.var(), arr_50.std()

(np.float64(-0.032932090814718026),
 np.float64(0.719348971570458),
 np.float64(0.8481444284851831))

In [17]:
#this default_rng is different. because it was in other cell. huh
X = random_num_generator.standard_normal((10 , 3))
print(X)
X.mean(axis = 0)
#X.mean(0)

[[-0.18486236 -0.68092954  1.22254134]
 [-0.15452948 -0.42832782 -0.35213355]
 [ 0.53230919  0.36544406  0.41273261]
 [ 0.430821    2.1416476  -0.40641502]
 [-0.51224273 -0.81377273  0.61597942]
 [ 1.12897229 -0.11394746 -0.84015648]
 [-0.82448122  0.65059279  0.74325417]
 [ 0.54315427 -0.66550971  0.23216132]
 [ 0.11668581  0.2186886   0.87142878]
 [ 0.22359555  0.67891356  0.06757907]]


array([0.12994223, 0.13527994, 0.25669717])

In [1]:
"hello world"[3:6]

'lo '

In [2]:
"hello world"[slice(3,6)]

'lo '

In [26]:
import numpy as np
np.linspace(0,10,5)
#beginning and end - inclusive. how many linearly spaced floats needed is the 3rd argument

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [32]:
np.arange(0,10,2)
#end is not inclusive. 3rd argument is the stepper

array([0, 2, 4, 6, 8])

In [38]:
A = np.arange(16).reshape(4,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [36]:
A[[1,3]]

array([[ 4,  5,  6,  7],
       [12, 13, 14, 15]])

In [37]:
A[:,[0,2]]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14]])

In [44]:
A[[1,3],[1,2]]
#expectation was to get the 2,4th rows and 2,3rd columns submatrix

array([ 5, 14])

In [45]:
A[[1,3]][:,[1,2]]
#first get the subset using rows. then select the columns

array([[ 5,  6],
       [13, 14]])

In [46]:
#convenience function
idx = np.ix_([1,3],[1,2])
A[idx]

array([[ 5,  6],
       [13, 14]])

In [54]:
#we can subset matrices efficiently using slicing
A[0:3:2,0:3:2]

array([[ 0,  2],
       [ 8, 10]])

In [60]:
keep_rows = np.zeros(A[0].shape, bool)
keep_rows[0:4:2]=True
keep_rows

array([ True, False,  True, False])

In [61]:
A[keep_rows]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [63]:
A[np.array([1,0,1,0])]

array([[4, 5, 6, 7],
       [0, 1, 2, 3],
       [4, 5, 6, 7],
       [0, 1, 2, 3]])

In [70]:
#2,4th rows. 1,3,4th columns
keep_cols = np.zeros(A[1].shape,bool)
keep_cols[[0,2,3]] = True
idx = np.ix_(keep_rows,keep_cols)
A[idx]

array([[ 0,  2,  3],
       [ 8, 10, 11]])

In [71]:
A[1]

array([4, 5, 6, 7])

In [73]:
total = 0
for x in [2,3,19]:
    for y in [0.2,0.3,0.5]:
        total+=x*y
print(total)

24.0


In [74]:
total = 0
for value,weight in zip([2,3,19],[0.2,0.3,0.5]):
    total += value * weight
print('weighted average is {0}'.format(total))

weighted average is 10.8


In [79]:
import pandas as pd
rng = np.random.default_rng(1)
A = rng.standard_normal((127,5))
M = rng.choice([0,np.nan], p=[0.8,0.2], size = A.shape)
A += M
D = pd.DataFrame(A, columns = [
    'food',
    'bar',
    'pickle',
    'juice',
    'coffee'])
D[:3]

food       bar    pickle     juice    coffee
0  0.345584  0.821618  0.330437 -1.303157       NaN
1       NaN -0.536953  0.581118  0.364572  0.294132
2       NaN  0.546713       NaN -0.162910 -0.482119

In [80]:
for col in D.columns:
    template = "Column '{0}' has {1:.2%} missing values"
    print(template.format(col, np.isnan(D[col]).mean() ))

Column 'food' has 16.54% missing values
Column 'bar' has 25.98% missing values
Column 'pickle' has 29.13% missing values
Column 'juice' has 21.26% missing values
Column 'coffee' has 22.83% missing values
