In [1]:
import numpy as np
import statsmodels.api as sm
from ISLP import load_data
from ISLP.models import (ModelSpec as MS,
                         summarize,
                         poly)
from sklearn.model_selection import train_test_split

from functools import partial
from sklearn.model_selection import \
     (cross_validate,
      KFold,
      ShuffleSplit)
from sklearn.base import clone
from ISLP.models import sklearn_sm

In [2]:
Auto = load_data('Auto')
Auto_train, Auto_valid = train_test_split(Auto,
                                         test_size=196,
                                         random_state=0)
# random seed set as 0, so that the same randomness will be used next time we execute the code and the results will be consistent

In [3]:
hp_mm = MS(['horsepower'])
X_train = hp_mm.fit_transform(Auto_train)
y_train = Auto_train['mpg']
model = sm.OLS(y_train, X_train)
results = model.fit()

In [4]:
X_valid = hp_mm.transform(Auto_valid)
y_valid = Auto_valid['mpg']
valid_pred = results.predict(X_valid)
np.mean((y_valid - valid_pred) ** 2)

np.float64(23.616617069669886)

In [5]:
# validation set MSE is 23.61%

In [6]:
def evalMSE(terms, response, train, test):
    
    mm = MS(terms)
    X_train = mm.fit_transform(train)
    y_train = train[response]

    X_test = mm.transform(test)
    y_test = test[response]

    results = sm.OLS(y_train, X_train).fit()
    test_pred = results.predict(X_test)

    return np.mean((y_test - test_pred)**2)

In [7]:
MSE = np.zeros(3)
for idx, degree in enumerate(range(1, 4)):
    MSE[idx] = evalMSE([poly('horsepower', degree)],
                       'mpg',
                       Auto_train,
                       Auto_valid)
MSE

array([23.61661707, 18.76303135, 18.79694163])

In [8]:
"""
the results will be different if we choose different splits or different seed number of the randomness
"""
# choosing random state as 3
Auto_train, Auto_valid = train_test_split(Auto,
                                         test_size=196,
                                         random_state=3)

MSE = np.zeros(3)
for idx, degree in enumerate(range(1,4)):
    MSE[idx] = evalMSE([poly('horsepower', degree)],
                        'mpg',
                        Auto_train,
                        Auto_valid)
MSE

array([20.75540796, 16.94510676, 16.97437833])

In [9]:
"""
LOOCV
"""

'\nLOOCV\n'

In [10]:
# sklearn_sm() wraps the scikit's cross-validation tools over the statsmodel's fit
# additional args : model_str -> model formula & model_args -> dictionary of additional args used to fit the model

"""
by default the cross validation thats run is 5 fold
if n is the number of observations, LOOCV is run
if the Y is binary or categorical, Stratified K fold is used

cross_validate returns a dictionary of results which includes test_score, train_score, fit_time, score_time
"""

hp_model = sklearn_sm(sm.OLS, MS(['horsepower']))
X, Y = Auto.drop(columns = ['mpg']), Auto['mpg']
# LOOCV. because cv = number of rows
cv_results = cross_validate(hp_model, X, Y, cv = Auto.shape[0])
cv_err = np.mean(cv_results['test_score'])
cv_err

np.float64(24.231513517929233)

In [11]:
"""
outer executes the function on each pair of the 2 matrices
in the above code, H is an array of horsepower values. 
in each loop, the X becomes a matrix of 
1,H0
1,H0,H1 
1,H0,H1,H2... so on. 
to be interpreted as mpg is polynomial function of horsepower
"""

cv_error = np.zeros(5)
H = np.array(Auto['horsepower'])
M = sklearn_sm(sm.OLS)
for i, d in enumerate(range(1,6)):
    X = np.power.outer(H, np.arange(d+1))
    M_CV = cross_validate(M,
                          X,
                          Y,
                          cv=Auto.shape[0])
    cv_error[i] = np.mean(M_CV['test_score'])
cv_error

array([24.23151352, 19.24821312, 19.33498406, 19.42443032, 19.03323829])

In [12]:
for i, d in enumerate(range(1,6)):
    print(i,d)

0 1
1 2
2 3
3 4
4 5


In [13]:
"""
np.power.outer(H, np.arange(d+1)) -> for each item in H, it prepares the polynomials. example below
H = np.array([1, 5, 10])
d = 3
np.arange(d+1) = [0, 1, 2, 3] (which are the powers)
X for 1 -> 1,1,1,1
X for 5 -> 1,5,25,125
X for 10 -> 1,10,100,1000
in effect, [1, H, H², H³]
1st column will be intercept, subsequent columns will be the powers of the values
"""
H = np.array([1, 5, 10])
d = 3
X = np.power.outer(H, np.arange(d+1))
X

array([[   1,    1,    1,    1],
       [   1,    5,   25,  125],
       [   1,   10,  100, 1000]])

In [14]:
"""
K fold cross validation
"""

'\nK fold cross validation\n'

In [15]:
cv_error = np.zeros(5)
cv = KFold(n_splits = 10,
           shuffle = True,
           random_state = 0) # use same splits for each degree
H = np.array(Auto['horsepower'])
M = sklearn_sm(sm.OLS)
for i, d in enumerate(range(1,6)):
    X = np.power.outer(H, np.arange(d+1))
    M_CV = cross_validate(M,
                          X,
                          Y,
                          cv = cv)
    cv_error[i] = np.mean(M_CV['test_score'])
cv_error

array([24.20766449, 19.18533142, 19.27626666, 19.47848403, 19.13721179])

In [16]:
"""
randomly shuffles the dataset and splits it into training and test sets over multiple iterations. 
Unlike K-Fold, it allows for independent sampling, meaning some data points may be repeated in the test sets across iterations, 
while allowing control over the number of iterations. 

this std or mean is not a valid estimate because there could be duplicates in the sample
"""

validation = ShuffleSplit(n_splits=1,
                          test_size=196,
                          random_state=0)
results = cross_validate(hp_model,
                         Auto.drop(['mpg'], axis=1),
                         Auto['mpg'],
                         cv=validation);
results['test_score']

array([23.61661707])

In [17]:
"""
bootstrapping

when you dont have a huge dataset and want to check how reliable is the accuracy of the model,
we can create multiple variations of the dataset with replacement of the data
and assess the standard error of the standard deviation of the dataset and estimated coefficient 
"""

'\nbootstrapping\n\nwhen you dont have a huge dataset and want to check how reliable is the accuracy of the model,\nwe can create multiple variations of the dataset with replacement of the data\nand assess the standard error of the standard deviation of the dataset and estimated coefficient \n'

In [18]:
Portfolio = load_data('Portfolio')

# calculate alpha - a ratio such that it maximizes the profit if invested in alpha amount in X and (1 - alpha) amount in Y
def alpha_func (D, idx):
    cov_ = np.cov(D[['X','Y']].loc[idx], rowvar=False)
    return (( cov_[1 ,1] - cov_[0 ,1]) /
            (cov_[0 ,0]+ cov_[1 ,1] - 2 * cov_[0 ,1]))

In [19]:
Portfolio.shape

(100, 2)

In [20]:
# calculating alpha using all observations
alpha_func (Portfolio , range (100))

np.float64(0.57583207459283)

In [21]:
# calculating alpha based on random observations, with duplicates 
rng = np.random.default_rng(0)
alpha_func(Portfolio, rng.choice(100, 100, replace=True))

np.float64(0.6074452469619004)

In [22]:
# bootstrap standard error
def boot_SE(func, D, n = None, B = 1000, seed = 0):
    rng = np.random.default_rng(seed)
    first_, second_ = 0,0
    n = n or D.shape[0]
    for _ in range(B):
        # find random n elements of indexes to use from the dataframe D
        idx = rng.choice(D.index, n, replace = True)
        # value is the alpha
        value = func(D, idx)        
        first_ += value
        second_ += value ** 2
    # first / B -> mean -> E[X]
    # second / B -> mean of X^2 -> E[X^2]
    
    # SE = sqrt(E[X^2] - (E[X])^2)
    return np.sqrt(second_ / B - (first_ / B)**2)

In [23]:
alpha_SE = boot_SE(alpha_func, Portfolio, B=1000, seed=0)
alpha_SE

np.float64(0.09118176521277699)

In [24]:
# estimating accuracy of linear regression model

In [35]:
Auto = load_data('auto')

In [47]:
# clone creates the fresh copy in this case, 
# since each bootstrap model should be fit for different samples and we dont want any learnt or scaled inputs from earlier
def boot_OLS(model_matrix, response, D, idx):
    D_ = D.iloc[idx]
    Y_ = D_[response]
    X_ = clone(model_matrix).fit_transform(D_)
    return sm.OLS(Y_, X_).fit().params

In [48]:
# new function hp_func will have the first 2 arguments of the boot_OLS function fixed to MS['horsepower'] and 'mpg'
hp_func = partial(boot_OLS, MS(['horsepower']), 'mpg')
hp_func?

Signature:      hp_func(D, idx)
Call signature: hp_func(*args, **kwargs)
Type:           partial
String form:    functools.partial(<function boot_OLS at 0x16bca1a80>, ModelSpec(terms=['horsepower']), 'mpg')
File:           /opt/anaconda3/lib/python3.13/functools.py
Docstring:     
Create a new function with partial application of the given arguments
and keywords.

In [50]:
rng = np.random.default_rng(0)
n_rows = Auto.shape[0]
np.array([hp_func(Auto, rng.choice(n_rows, n_rows, replace=True)) for _ in range(10)])

array([[39.88064456, -0.1567849 ],
       [38.73298691, -0.14699495],
       [38.31734657, -0.14442683],
       [39.91446826, -0.15782234],
       [39.43349349, -0.15072702],
       [40.36629857, -0.15912217],
       [39.62334517, -0.15449117],
       [39.0580588 , -0.14952908],
       [38.66688437, -0.14521037],
       [39.64280792, -0.15555698]])

In [52]:
# calculate the standard error of the estimates of OLS model defined in boot_OLS
hp_se = boot_SE(hp_func, Auto, B = 1000, seed = 10)
hp_se

intercept     0.848807
horsepower    0.007352
dtype: float64

In [53]:
# the std error for intercept is 0.848 and for the horsepower coefficient its 0.007

In [54]:
hp_model.fit(Auto, Auto['mpg'])
model_se = summarize(hp_model.results_)['std err']
model_se

intercept     0.717
horsepower    0.006
Name: std err, dtype: float64

In [55]:
# from the model summarize, this is the estimated standard error.
# this is an underestimated value because of the assumptions of the formulas used - 
# assumptions that the errors ϵi for each observation have common variance σ2 and are uncorrelated